blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/agQ9mRdHMZ
    about: Ask anything non-bug/feature related here (such as "How does XYZ work?" or "Why does ZYX work the way it does?")
